/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DynamicGlobalProperties {
  headBlockId: string
}
export function getGlobalDynamicProperties(): Promise<DynamicGlobalProperties>
